<a href="https://colab.research.google.com/github/iamkishore0/DS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Basics**

In [1]:
#Import Numpy Library
import numpy as np

In [2]:
#Create 1 dimentional array with shape of 3
a = np.array([1,2,3])

In [3]:
print(a)
print(a.shape)
print(type(a))

[1 2 3]
(3,)
<class 'numpy.ndarray'>


In [4]:
#Create 1 dimentional array with shape of 3
b = np.array([1,2,3,4])

In [5]:
print(b)
print(b.shape)
print(type(b))

[1 2 3 4]
(4,)
<class 'numpy.ndarray'>


In [6]:
#Array with decimals
c = np.array([1.1,2.2,3.3])

In [7]:
print(c)       
print(c.shape) 
print(type(c))

[1.1 2.2 3.3]
(3,)
<class 'numpy.ndarray'>


In [8]:
#Access elements and data types
print(a[0])       
print(b[2])
print(c[1])       
print(type(a[2])) 
print(type(b[1]))
print(type(c[2]))

1
3
2.2
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.float64'>


In [9]:
#Create two dimentional array with shape 2
d = np.array([[1,2],[3,4]])

In [10]:
print(d)
print(d.shape)

[[1 2]
 [3 4]]
(2, 2)


In [11]:
#Create three dimentional array with shape 2
e = np.array([[1,2],[3,4],[4,5]])

In [12]:
print(e)
print(e.shape)

[[1 2]
 [3 4]
 [4 5]]
(3, 2)


# **Ones and Zeros**

In [13]:
#Create a 2*2 array - filled with ones
f = np.ones((2,2))

In [14]:
print(f)            
print(f.shape)       
print(type(f))       
print(type(f[0][0]))

[[1. 1.]
 [1. 1.]]
(2, 2)
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [15]:
##Create a 3*3 array - filled with zeros
g = np.zeros((3,3))

In [16]:
print(g)             
print(g.shape)       
print(type(g))       
print(type(g[0][0]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
<class 'numpy.ndarray'>
<class 'numpy.float64'>


In [17]:
#Create 2*2 array filled with random numbers
h = np.random.random((2,2))

In [18]:
print(h)        
print(h.shape)

[[0.47099193 0.12552517]
 [0.01467698 0.53690978]]
(2, 2)


In [19]:
#Create 6*6 array filled with random numbers
i = np.random.random((6,6))

In [20]:
print(i)        
print(i.shape)

[[0.24782558 0.38051431 0.43143649 0.98889659 0.73104748 0.44333712]
 [0.62567819 0.94503686 0.75906925 0.72463693 0.99042464 0.52315627]
 [0.2605941  0.89177038 0.06849802 0.43883378 0.18641824 0.63993245]
 [0.70473543 0.01607871 0.00525221 0.15149726 0.29519526 0.63028694]
 [0.52319359 0.75702647 0.49199196 0.96685372 0.29486046 0.87139638]
 [0.96445936 0.68938701 0.40658551 0.98696046 0.81870835 0.56504313]]
(6, 6)


# **Array Math**

In [21]:
add = a + c
print ("addition")
print(add)
print(np.add(a,c))

addition
[2.1 4.2 6.3]
[2.1 4.2 6.3]


In [22]:
sub = a - c
print ("subtraction")
print(sub)               
print(np.subtract(a,c)) 

subtraction
[-0.1 -0.2 -0.3]
[-0.1 -0.2 -0.3]


In [23]:
mul = a * c
print ("multiplication")
print(mul)                
print(np.multiply(a,c)) 

multiplication
[1.1 4.4 9.9]
[1.1 4.4 9.9]


In [24]:
div = a / c
print ("division")
print(div) 
print(np.divide(a,c))   

division
[0.90909091 0.90909091 0.90909091]
[0.90909091 0.90909091 0.90909091]


# **Array Concat**

In [25]:
abc = np.array([1,2,3])
xyz = np.array([4,5,6])

In [26]:
print(abc.shape)
print(xyz.shape)  

(3,)
(3,)


In [27]:
concat = np.concatenate((abc, xyz))  

In [28]:
print(concat)      
print(concat.shape) 

[1 2 3 4 5 6]
(6,)


In [29]:
deg = np.array([[1,2,3],[4,5,6]])
uvw = np.array([[40,40,40],[50,50,50]])

In [30]:
print(deg.shape)     
print(uvw.shape) 

(2, 3)
(2, 3)


In [31]:
concat_a = np.concatenate((deg, uvw), axis=0)
concat_b = np.concatenate((deg, uvw), axis=1)


In [32]:
print(concat_a)
print(concat_a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]
 [50 50 50]]
(4, 3)


In [33]:
print(concat_b)
print(concat_b.shape)

[[ 1  2  3 40 40 40]
 [ 4  5  6 50 50 50]]
(2, 6)


In [34]:
v_stack  = np.vstack((deg,uvw))
h_stack  = np.hstack((deg,uvw))

In [36]:
print(concat_a) 
print(v_stack) 
print(concat_a.shape)

[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]
 [50 50 50]]
[[ 1  2  3]
 [ 4  5  6]
 [40 40 40]
 [50 50 50]]
(4, 3)


In [37]:
print(concat_b)        
print(h_stack)         
print(concat_b.shape)

[[ 1  2  3 40 40 40]
 [ 4  5  6 50 50 50]]
[[ 1  2  3 40 40 40]
 [ 4  5  6 50 50 50]]
(2, 6)


# **Array Reshape**

In [38]:
a = np.array([[1,1,1],[2,2,2]])

In [39]:
print(a)
print(a.shape)

[[1 1 1]
 [2 2 2]]
(2, 3)


In [40]:
b = np.reshape(a, 6)

In [41]:
print(b)
print(b.shape)

[1 1 1 2 2 2]
(6,)


In [42]:
c = np.reshape(b, (3,2))

In [43]:
print(c)              
print(c.shape) 

[[1 1]
 [1 2]
 [2 2]]
(3, 2)


In [44]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [45]:
print(c)        
print(c.shape) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [46]:
d = np.ravel(c)
e = c.flatten()

In [47]:
print(d) 
print(e)    

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


# **Expand Dimensions**

In [49]:
a = np.array([500,200,100])

In [50]:
# insert a new axis along the row
b = np.expand_dims(a, axis=0)  

# insert a new axis along the column
c = np.expand_dims(a, axis=1)

print(b)            
print(b.shape)     

print(c)           
print(c.shape) 

[[500 200 100]]
(1, 3)
[[500]
 [200]
 [100]]
(3, 1)


# Transpose

In [51]:
x = np.array([[1, 2], [3, 4]])
print (x)
#getting the transpose
print (x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


# **Unique**

In [52]:
m = np.array([1,2,1,1,4])

# get the unique elements and thier indexes
n, indices = np.unique(m, return_index=True)

print(n)        
print(indices)

[1 2 4]
[0 1 4]
